name: binder
description: A starting point for Dart libraries or applications.
version: 1.0.0
homepage: https://www.binder.kabagouda.com

environment:
  sdk: '>=2.14.1 <3.0.0'

dependencies:
  path: ^1.8.0
  build_runner: ^2.1.4
  build_web_compilers: ^3.2.1
  browser_launcher: ^1.0.0
  equatable: ^2.0.3

dev_dependencies:
  lints: ^1.0.0
  test: ^1.16.0
