name: binder
description: A starting point for Dart libraries or applications.
version: 1.0.0
homepage: https://www.binder.kabagouda.com

environment:
  sdk: '>=2.16.1 <3.0.0'

dependencies:
  path: ^1.8.0
  # build_runner: ^2.1.4
  # build_web_compilers: ^3.2.1
  yaml: ^3.1.0
  # browser_launcher: ^1.0.0
  http: ^0.13.4

dev_dependencies:
  lints: ^1.0.0
  test: ^1.16.0
  ansicolor: ^2.0.1
  

executables:
  binder: 